version: "3"

services:
  app:
    container_name: angular-app
    build: .
    ports:
      - "4200:4200"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: "node_modules/.bin/ng serve --host 0.0.0.0 --port 4200"
