FROM trion/ng-cli as builder
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm ci  --debug 
COPY . .
RUN ng build --prod


FROM node:12-alpine3.10
WORKDIR /usr/src/app
COPY --from=builder  /app/dist/* ./dist/
COPY deploy deploy
COPY package*.json ./
RUN npm ci --only=production
CMD [ "node", "./deploy/server.js" ]

